### PR TITLE
Updates to web app to improve authentication flow, UI on smaller screened phones and address bugs

### PR DESCRIPTION
**Pull request by itemir**
This PR introduces several enhancements and fixes to the web app:

1. **Enhanced Authentication Flow**: The authentication process is now streamlined. Upon loading the web app, user authentication is immediately verified. If the user is not authenticated, they are promptly redirected to the login page.

2. **Improved UI for Smaller Screens**: The user interface has been optimized for better performance on smaller screens, particularly mobile devices. The `LayerControl` component, which could previously be obscured by other buttons, is now centered for easier access.

3. **Anchor Setting Bug Fix**: A bug related to setting the anchor when a depth value is missing has been resolved.

### CODE REVIEW

**Comment by sbender9** [comment]
The commits are a mess!

**Comment by itemir** [comment]
I think it is just the history, those are already committed. The delta is a single commit. I don't know why all those show up but 731b177003a3c1eb10d6d84cf93f6abadb82c556 is a merge of everything that has been committed and 3a99f2d1ee92de1ea4770b6988778103f2615ab7 is the only commit in this PR.

I may need to re-fork to get rid of that history.

**Comment by sbender9** [comment]
You should rebase your fork. I find it best to create a branch for each pr. Then rebase your fork and create a new branch for the next pr.

**Comment by itemir** [comment]
I thought the merge with your master was a rebase but apparently not. Let's commit this if ok, I am not sure how to retrace this back to a different merge config otherwise. I will either re-fork or find a better way to rebase it before we make more changes.

**Pull request merged**
