### PR TITLE
customizable delay between alarm notifications

### PR DESCRIPTION
**Pull request by davidsanner**
Fix/Update: Audio alarm notifications repeating at too fast causing collisions / notifications voiced on top of each other.

### CODE REVIEW

**Comment by sbender9** [comment]
I think I am just going to make so that it only sends the notification once. Does that work for you?

**Comment by davidsanner** [comment]
If the anchor has dragged / is dragging I would want a repeated notification - like an alarm clock, so that you don't sleep through it or miss it.  User defined from continuous, once a minute, hour, etc.
(OpenCPN alarm is continuous ... which definitely gets your attention but OpenCPN has to be running.)

**Comment by davidsanner** [comment]
And OpenCPN's anchor alarm doesn't work w/  WilhelmSK ;)

**Comment by sbender9** [comment]
I am a little confused. In general in Signal K, it is normal to send a notification just once. It is up the client to decide how to deal with that. And I think this goes back to the original issue you are trying to fix. What ever you are using to deal with notifications is not doing it correctly. 

Can you go back and describe better the original issue?

**Comment by sbender9** [comment]
> And OpenCPN's anchor alarm doesn't work w/  WilhelmSK ;)  

I don't know anything about OpenPNS's anchor alarm. And WilhelmSK does not talk to OpenCPN in any way. Doesn't sound like they are integrating with SK very well.

**Comment by davidsanner** [comment]
Sorry if my use case wasn't clear.  I have signalk-audio-notifications enabled so when anchor alarm is active and the vessel goes outside of the boundary I get multiple/continuous audio notifications all 'speaking' at the same time.  They are happening so rapidly I can't even understand what it's saying.  It sounds like around 5 are overlapped at the same time.

When I added a 6 second delay between sending audio alerts their is no overlap and now when the anchor-alarm is in alarm state it repeats the audio alarm message and a usable rate and does it continuously, which I think is desirable.

I added a repeatDelay in the checkPosition function in the same block of code that delays the start time for the initial alert.  This works well but it could be moved.

I guess another option would be to only set the state once (send the audio alarm once?) and then have signalk-audio-notifications handle the repeat logic though that sounds more involved and might have it's own set of issues.  Thx.

**Comment by sbender9** [comment]
sounds like a bug in signalk-audio-notifications.

**Comment by sbender9** [comment]
It should just be looking at the alarm "state" and "method". 

My signalk-fusion plugin would be a good example to look at. 


You could also use that even if you don't have a fusion stereo. It will output alarms to the audio out.

**Comment by davidsanner** [comment]
It looks like signalk-audio-notifications  just subscribes to notifications events (if that's the proper terminology) and does a single audio alert with "Repeat" for any new alarm notification. 

      if (notification.type === 'alarm') {
        playable = `${notification.message} Repeat: ${notification.message}`;
      }

I'll take a look at your fusion code.  It seems the audio-notification would have to continuously look (query?) for any current notification in alarm state to be able to repeat while alarm is active.  Thx.

**Pull request closed without merging**
