### PR TITLE
Add WebApp to control anchor alarm from within a web browser

### PR DESCRIPTION
**Pull request by VibroAxe**
An update to https://github.com/sbender9/signalk-anchoralarm-plugin/pull/14 with bug fixes and additional functionality

# Original PR
This PR adds a web app to the plugin, allowing it to control from a browser. User needs to be logged into SignalK UI for this to work.

# Feature Improvements
Added a layer control to sort the openstreetmap, satellite and openseamap layers/overlays. Defaults can be controlled via querystring to allow easy embedding via iframe

| OpenStreetMap | Satellite | OpenSeaMap | Url String |
| ------------- | --------- | ---------- | -----------|
| X | - | - | / |
| X | - | X | /?openseamap |
| - | X | - | /?satellite |
| - | X | X | /?satellite&openseamap |

# Also fixes the following issues from @itemir PR
* If self.navigation.headingTrue does not exist the the webapp crashes and wont start. It's possible for people to not have this if the chart plotter doesn't have a magneticCompass attached.
* Capture this using nullish (set to 0 check is already present)
* During startup/handshaking it's possible to have AIS information about a vessel, but not it's name, nullish to end up with "undefined" vessel name and remove errors in console
* If the user is not logged in the Drop Anchor fails silently. Added 401 capture & redirect to handle this

### CODE REVIEW

**Comment by VibroAxe** [comment]
@sbender9 I've submitted a new PR directly on here as there is no update from @itemir to fix/merge the pugs in the original PR #14

Hopefully you would consider merging these changes

**Comment by sbender9** [comment]
Sorry fir the delay... can you test signalk-anchoralarm-plugin@1.11.0-beta.1?

**Comment by itemir** [comment]
Didn't work for me too. Will debug later today.

**Comment by tkurki** [comment]
Instead of or in addition to hard coded internet map sourcesconsider supporting SK charts. That would allow people to use local offline maps.

**Comment by VibroAxe** [comment]
> Looks like it is not quite working. Not sure if it is my fault

Let me check tomorrow, I redid a pr against @itemir master, might have missed some commits here. I'm only on mobile now but will check in the morning

**Comment by itemir** [comment]
Can you test with pull request #20 ? Looks like code refactoring had an impact on when SignalK starts returning data and it was requiring a manual reload or a forced delayed reload. I refactored the webapp to avoid reloads and fixed a bug with AIS name parsin as well.

@VibroAxe thanks for the additional layer support and error handling. However, I changed the default map layer to satellite . I appreciate OSM maps but I intentionally wanted the satellite view for the default (makes it easier to see shallow areas!)

**Pull request merged**
